version: "3.8"

services:
  frontend:
    tty: true
    container_name: exotic-frontend-dev
    image: exotic-frontend-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
